"""
One-shot extract of the 8 Cinderhaven tables this project consumes
into a self-contained SQLite file at data/cinderhaven_extract.db.

Source: cinderhaven-data repo's built database (172 MB, regenerable
from that repo's scripts). This extract is ~14k rows across 8 tables
and is safe to commit to this repo.

Excluded: scan_data (~1.19M rows, ~140 MB) — not needed for
short-ship-cost analysis (POS sell-through is a different data layer).
"""
from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = Path(r"C:/Users/mssha/projects/active/cinderhaven-data/data/cinderhaven_product_master.db")
DEST = REPO / "data" / "cinderhaven_extract.db"

TABLES = [
    "product_master",
    "sku_costs",
    "stores",
    "distribution_log",
    "promotions",
    "price_history",
    "chargebacks",
    "retailer_rules",
]


def main() -> int:
    if not SRC.exists():
        print(f"ERROR: source DB not found at {SRC}", file=sys.stderr)
        return 1

    DEST.parent.mkdir(parents=True, exist_ok=True)
    if DEST.exists():
        DEST.unlink()

    src = sqlite3.connect(SRC)
    src.row_factory = sqlite3.Row
    dest = sqlite3.connect(DEST)

    cur_src = src.cursor()
    cur_dest = dest.cursor()

    counts: dict[str, int] = {}
    for table in TABLES:
        # Pull the source CREATE TABLE statement so column types,
        # NOT NULL flags, and PK definitions are preserved verbatim.
        cur_src.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?",
            (table,),
        )
        row = cur_src.fetchone()
        if row is None:
            print(f"ERROR: table {table} not found in source", file=sys.stderr)
            return 1
        cur_dest.execute(row[0])

        cur_src.execute(f"SELECT * FROM {table}")
        rows = cur_src.fetchall()
        if rows:
            placeholders = ",".join(["?"] * len(rows[0]))
            cur_dest.executemany(
                f"INSERT INTO {table} VALUES ({placeholders})",
                [tuple(r) for r in rows],
            )
        counts[table] = len(rows)

    # Carry over any non-autogenerated indexes too.
    cur_src.execute(
        "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL "
        "AND tbl_name IN (" + ",".join("?" * len(TABLES)) + ")",
        TABLES,
    )
    for (idx_sql,) in cur_src.fetchall():
        cur_dest.execute(idx_sql)

    dest.commit()
    dest.close()
    src.close()

    size_mb = os.path.getsize(DEST) / (1024 * 1024)
    print(f"Wrote {DEST}  ({size_mb:.2f} MB)")
    total = 0
    for t, n in counts.items():
        print(f"  {t:<24} {n:>8} rows")
        total += n
    print(f"  {'TOTAL':<24} {total:>8} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
